# Generated by Django 5.0.6 on 2024-07-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('number_people', models.IntegerField()),
                ('number_beds_one', models.IntegerField()),
                ('number_beds_two', models.IntegerField()),
                ('animal_check', models.BooleanField()),
                ('price', models.IntegerField()),
                ('square_info', models.IntegerField()),
                ('type_housing', models.CharField(max_length=100)),
                ('time_stay', models.CharField(max_length=100)),
                ('time_leave', models.CharField(max_length=100)),
                ('short_desc', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('owner', models.IntegerField()),
                ('img_src', models.CharField(max_length=100)),
            ],
        ),
    ]
