# Generated by Django 5.0.6 on 2024-08-02 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('img_src', models.CharField(max_length=300)),
                ('clock_entry', models.CharField(max_length=100)),
                ('clock_leave', models.CharField(max_length=100)),
                ('min_length_of_stay', models.IntegerField()),
                ('max_length_of_stay', models.IntegerField()),
                ('animal_check', models.BooleanField()),
                ('smoking_check', models.BooleanField()),
                ('party_check', models.BooleanField()),
                ('docs_check', models.BooleanField()),
                ('kids_check', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('drier', models.BooleanField()),
                ('towel', models.BooleanField()),
                ('bed_linen', models.BooleanField()),
                ('tv', models.BooleanField()),
                ('microwave', models.BooleanField()),
                ('electric_kettle', models.BooleanField()),
                ('balcony', models.BooleanField()),
                ('params', models.CharField(max_length=200)),
                ('count_beds', models.IntegerField()),
                ('square', models.IntegerField()),
                ('count_people', models.IntegerField()),
                ('sleeping_places', models.IntegerField()),
                ('beds_info', models.CharField(max_length=200)),
                ('type_flats', models.CharField(max_length=200)),
                ('short_desc', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_ads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_lease', models.DateField()),
                ('end_lease', models.DateField()),
                ('approve_status', models.BooleanField(default=True)),
                ('lease_end_status', models.BooleanField(default=False)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.ad')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('count_reviews', models.IntegerField(default=0)),
                ('sum_rating', models.IntegerField(default=0)),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.ad')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_has_as_favorite', to='core.ad')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('text', models.TextField()),
                ('rating', models.IntegerField()),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.reservation')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.ad')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
