# Generated by Django 5.0.6 on 2024-07-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('data_stay', models.DateField(blank=True)),
                ('data_leave', models.DateField(blank=True)),
                ('number_adults', models.IntegerField()),
                ('number_kids', models.IntegerField()),
                ('animal_check', models.BooleanField()),
                ('price', models.IntegerField()),
                ('number_beds', models.IntegerField()),
                ('square_info', models.IntegerField()),
                ('type_housing', models.CharField(max_length=100)),
                ('short_desc', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('owner', models.IntegerField()),
                ('img_src', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
