# Generated by Django 5.0.6 on 2024-08-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paymentreceipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='owner',
        ),
    ]
