# Generated by Django 5.0.6 on 2024-07-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_number_adults_announcements_number_beds_one_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcements',
            new_name='Ads',
        ),
    ]
