# Generated by Django 5.0.6 on 2024-08-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_paymentreceipt_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='approve_status',
            field=models.BooleanField(default=False),
        ),
    ]
