# Generated by Django 5.0.6 on 2024-08-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_ad_img_src_ad_cash_back_ad_fast_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='address_lat',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='address_lon',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
