# Generated by Django 5.0.6 on 2024-08-16 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.CharField()),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('patronymic', models.CharField()),
                ('phone_number', models.CharField()),
                ('email', models.CharField()),
                ('super_lessor', models.BooleanField(default=False)),
                ('perfect_cleanliness', models.BooleanField(default=False)),
                ('traveler', models.BooleanField(default=False)),
                ('inspector', models.BooleanField(default=False)),
            ],
        ),
    ]
